name: ci

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # ubuntu-18.04 currently same as ubuntu-latest
        os: [ubuntu-16.04, ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc musl-dev libxml2-dev libxslt-dev python-dev
      if: runner.os == 'Linux'
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Install python packages
      run: |
        pipenv install --dev
    - name: List system version
        run: |
          pipenv run sysver
    - name: Run tests
      run: |
        pipenv run tests
    - name: Lint with black
      run: |
        pipenv run black --check .
